// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package layer2

// Catalog is a collection controls, threats, and capabilities.
type Catalog struct {
	Metadata *Metadata `json:"metadata,omitempty"`

	ControlFamilies []ControlFamily `json:"control_families,omitempty"`

	Threats []Threat `json:"threats,omitempty"`

	Capabilities []Capability `json:"capabilities,omitempty"`
}

type Metadata struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Version string `json:"version,omitempty"`
}

type Category struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`
}

type ControlFamily struct {
	Title string `json:"title"`

	Description string `json:"description"`

	Controls []Control `json:"controls"`
}

type Control struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Objective string `json:"objective"`

	Requirements []AssessmentRequirement `json:"requirements"`
}

type Threat struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Capabilities []Mapping `json:"capabilities"`

	Mappings []Mapping `json:"mappings,omitempty"`
}

type Capability struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`
}

type MappingReference struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Version string `json:"version"`

	Description string `json:"description,omitempty"`

	Url string `json:"url,omitempty"`
}

type Mapping struct {
	Identifiers []string `json:"identifiers"`
}

type AssessmentRequirement struct {
	Id string `json:"id"`

	Text string `json:"text"`

	Applicability []string `json:"applicability"`

	Recommendation string `json:"recommendation,omitempty"`
}
