// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package layer2

type Catalog struct {
	Metadata *Metadata `json:"metadata,omitempty"`

	ControlFamilies []ControlFamily `json:"control-families,omitempty"`

	Threats []Threat `json:"threats,omitempty"`

	Capabilities []Capability `json:"capabilities,omitempty"`

	SharedControls []Mapping `json:"shared-controls,omitempty"`

	SharedThreats []Mapping `json:"shared-threats,omitempty"`

	SharedCapabilities []Mapping `json:"shared-capabilities,omitempty"`
}

type Metadata struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Version string `json:"version,omitempty"`

	LastModified string `json:"last-modified,omitempty"`

	ApplicabilityCategories []Category `json:"applicability-categories,omitempty"`

	MappingReferences []MappingReference `json:"mapping-references,omitempty"`
}

type Category struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`
}

type ControlFamily struct {
	Title string `json:"title"`

	Description string `json:"description"`

	Controls []Control `json:"controls"`
}

type Control struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Objective string `json:"objective"`

	AssessmentRequirements []AssessmentRequirement `json:"assessment-requirements"`

	GuidelineMappings []Mapping `json:"guideline-mappings,omitempty"`

	ThreatMappings []Mapping `json:"threat-mappings,omitempty"`
}

type Threat struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Capabilities []Mapping `json:"capabilities"`

	ExternalMappings []Mapping `json:"external-mappings,omitempty"`
}

type Capability struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`
}

type MappingReference struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Version string `json:"version"`

	Description string `json:"description,omitempty"`

	Url string `json:"url,omitempty"`
}

type Mapping struct {
	ReferenceId string `json:"reference-id"`

	Identifiers []string `json:"identifiers"`
}

type AssessmentRequirement struct {
	Id string `json:"id"`

	Text string `json:"text"`

	Applicability []string `json:"applicability"`

	Recommendation string `json:"recommendation,omitempty"`
}
